Clickable boards
AbstractPlay/renderer pull request #9
Opened 2021-10-19 02:22 UTC by paulvanwamelen

Infrastructure for clickable boards and a working example for "squares-checkered".

2021-10-21 18:01 UTC, Perlkonig requested changes
This looks great. I just have one concern. This makes `boardClick` a required argument to the `render` function. But you've also added it as optional in IRendererOptions. Does that not throw an error if you don't pass a `boardClick`? Can you make it so that it is always optional and confirm that everything else works if it is omitted?

2021-10-21 18:01 UTC, Perlkonig commented on src/renderers/homeworlds.ts
> +    public render(json: APRenderRep, draw: Svg, boardClick: (row: number, col: number, piece: string) => void,
This makes `boardClick` a mandatory argument. Would this be better specified in the `IRenderOptions` interfaces and made optional?

2021-10-21 18:01 UTC, Perlkonig commented on src/index.ts
> +    boardClick?: (row: number, col: number, piece: string) => void;
I see you added it to the render options as optional, but isn't this overridden by the required argument added to `render()`?

2021-10-21 18:01 UTC, Perlkonig commented on src/RendererBase.ts
> +    public abstract render(json: APRenderRep, draw: Svg, boardClick: (row: number, col: number, piece: string) => void,
This makes `boardClick` a required parameter.

2021-10-22 01:18 UTC, paulvanwamelen commented on src/renderers/homeworlds.ts
> +    public render(json: APRenderRep, draw: Svg, boardClick: (row: number, col: number, piece: string) => void,
Yes, it is mandatory on the extensions of the RenderBase class, but we only call the render function from index.ts and it says:
```export function render(json: APRenderRep, opts = {} as IRenderOptions)```
where the optional boardClick from IRenderOptions kicks in. It then does:
```
    let boardClick: (row: number, col: number, piece: string) => void = (row, col, piece) => undefined;
    if (("boardClick" in opts) && (opts.boardClick != null) ) {
        boardClick = opts.boardClick;
    }
```
before it calls `renderer.render` with this boardClick.
Point is, to the outside world it is optional (and I've tested that). Does that address your concern?

2021-10-22 02:26 UTC, Perlkonig commented
Sorry for misunderstanding. Thanks again.

2021-10-22 02:26 UTC, merged